import type { ThemeSpec } from "../types";

export const bloombergDarkTheme: ThemeSpec = {
  id: "theme_bloomberg_dark",
  name: "Bloomberg Dark",
  style: "bloomberg_dark",
  colors: {
    primary: "#FFA726",
    secondary: "#78909C",
    accent: "#00E5FF",
    background: "#121212",
    surface: "#1E1E1E",
    textPrimary: "#F5F5F5",
    textSecondary: "#9E9E9E",
    textInverse: "#121212",
    border: "#333333",
    success: "#00E676",
    warning: "#FFAB40",
    error: "#FF5252",
    chartColors: [
      "#00E5FF",
      "#FFA726",
      "#00E676",
      "#FF5252",
      "#7C4DFF",
      "#FFD740",
      "#FF4081",
      "#64FFDA",
    ],
  },
  typography: {
    titleFont: "Bloomberg Plex",
    bodyFont: "Bloomberg Plex",
    monoFont: "Bloomberg Mono",
    titleSize: 36,
    subtitleSize: 22,
    bodySize: 16,
    captionSize: 13,
    titleWeight: "600",
    bodyWeight: "normal",
    lineHeight: 1.35,
  },
  spacing: {
    slidePaddingX: 0.9,
    slidePaddingY: 0.6,
    elementGap: 0.3,
    sectionGap: 0.6,
  },
  shapes: {
    cornerRadius: 6,
    lineWidth: 1,
    lineColor: "#444444",
  },
  chart: {
    axisColor: "#616161",
    gridColor: "#2C2C2C",
    labelColor: "#BDBDBD",
    fontFamily: "Bloomberg Mono",
  },
  image: {
    borderRadius: 6,
    overlayOpacity: 0.5,
    overlayColor: "#000000",
  },
  density: "high",
  defaultVisualIntensity: "medium",
};
