import type { ThemeSpec } from "../types";

export const darkEleganceTheme: ThemeSpec = {
  id: "theme_dark_elegance",
  name: "Dark Elegance",
  style: "dark_elegance",
  colors: {
    primary: "#e94560",
    secondary: "#8b8b8b",
    accent: "#f5c518",
    background: "#1a1a2e",
    surface: "#16213e",
    textPrimary: "#eaeaea",
    textSecondary: "#a0a0b0",
    textInverse: "#1a1a2e",
    border: "#2a2a4a",
    success: "#00d4aa",
    warning: "#f5c518",
    error: "#e94560",
    chartColors: [
      "#e94560",
      "#f5c518",
      "#00d4aa",
      "#4a6cf7",
      "#ff6b6b",
      "#48dbfb",
      "#ff9ff3",
      "#54a0ff",
    ],
  },
  typography: {
    titleFont: "Playfair Display",
    bodyFont: "Inter",
    monoFont: "JetBrains Mono",
    titleSize: 38,
    subtitleSize: 22,
    bodySize: 16,
    captionSize: 13,
    titleWeight: "700",
    bodyWeight: "normal",
    lineHeight: 1.4,
  },
  spacing: {
    slidePaddingX: 1.0,
    slidePaddingY: 0.7,
    elementGap: 0.35,
    sectionGap: 0.7,
  },
  shapes: {
    cornerRadius: 8,
    lineWidth: 1,
    lineColor: "#3a3a5a",
  },
  chart: {
    axisColor: "#4a4a6a",
    gridColor: "#2a2a4a",
    labelColor: "#a0a0b0",
    fontFamily: "JetBrains Mono",
  },
  image: {
    borderRadius: 8,
    overlayOpacity: 0.4,
    overlayColor: "#1a1a2e",
  },
  density: "medium",
  defaultVisualIntensity: "high",
};
