import type { ThemeSpec } from "../types";

export const mckinseyConsultingTheme: ThemeSpec = {
  id: "theme_mckinsey_consulting",
  name: "McKinsey Consulting",
  style: "mckinsey_consulting",
  colors: {
    primary: "#003A70",
    secondary: "#5C6B7A",
    accent: "#0078D4",
    background: "#FFFFFF",
    surface: "#F8F9FA",
    textPrimary: "#1A1A2E",
    textSecondary: "#5C6B7A",
    textInverse: "#FFFFFF",
    border: "#D0D5DD",
    success: "#0D7C3E",
    warning: "#C77C14",
    error: "#C4314B",
    chartColors: [
      "#003A70",
      "#0078D4",
      "#0D7C3E",
      "#C77C14",
      "#7B2D8E",
      "#C4314B",
      "#00857D",
      "#6B5B95",
    ],
  },
  typography: {
    titleFont: "Georgia",
    bodyFont: "Helvetica Neue",
    monoFont: "Consolas",
    titleSize: 32,
    subtitleSize: 20,
    bodySize: 15,
    captionSize: 12,
    titleWeight: "bold",
    bodyWeight: "normal",
    lineHeight: 1.45,
  },
  spacing: {
    slidePaddingX: 0.7,
    slidePaddingY: 0.5,
    elementGap: 0.25,
    sectionGap: 0.5,
  },
  shapes: {
    cornerRadius: 4,
    lineWidth: 1,
    lineColor: "#D0D5DD",
  },
  chart: {
    axisColor: "#98A2B3",
    gridColor: "#E4E7EC",
    labelColor: "#344054",
    fontFamily: "Helvetica Neue",
  },
  image: {
    borderRadius: 4,
    overlayOpacity: 0.25,
    overlayColor: "#1A1A2E",
  },
  density: "high",
  defaultVisualIntensity: "low",
};
