import type { ThemeSpec } from "../types";

export const minimalLightTheme: ThemeSpec = {
  id: "theme_minimal_light",
  name: "Minimal Light",
  style: "minimal_light",
  colors: {
    primary: "#333333",
    secondary: "#888888",
    accent: "#0066ff",
    background: "#fafafa",
    surface: "#ffffff",
    textPrimary: "#1a1a1a",
    textSecondary: "#666666",
    textInverse: "#ffffff",
    border: "#e0e0e0",
    success: "#22c55e",
    warning: "#f59e0b",
    error: "#ef4444",
    chartColors: [
      "#0066ff",
      "#333333",
      "#22c55e",
      "#f59e0b",
      "#ef4444",
      "#8b5cf6",
      "#06b6d4",
      "#ec4899",
    ],
  },
  typography: {
    titleFont: "Helvetica Neue",
    bodyFont: "Helvetica Neue",
    monoFont: "Menlo",
    titleSize: 34,
    subtitleSize: 20,
    bodySize: 15,
    captionSize: 12,
    titleWeight: "600",
    bodyWeight: "normal",
    lineHeight: 1.5,
  },
  spacing: {
    slidePaddingX: 1.2,
    slidePaddingY: 0.8,
    elementGap: 0.4,
    sectionGap: 0.8,
  },
  shapes: {
    cornerRadius: 4,
    lineWidth: 1,
    lineColor: "#e0e0e0",
  },
  chart: {
    axisColor: "#cccccc",
    gridColor: "#f0f0f0",
    labelColor: "#888888",
    fontFamily: "Menlo",
  },
  image: {
    borderRadius: 4,
    overlayOpacity: 0.3,
    overlayColor: "#ffffff",
  },
  density: "low",
  defaultVisualIntensity: "low",
};
