import type { ThemeSpec } from "../types";

export const techGradientTheme: ThemeSpec = {
  id: "theme_tech_gradient",
  name: "Tech Gradient",
  style: "tech_gradient",
  colors: {
    primary: "#00d2ff",
    secondary: "#7b68ee",
    accent: "#ff6b6b",
    background: "#0f0c29",
    surface: "#1a1640",
    textPrimary: "#e8e8ff",
    textSecondary: "#9898b8",
    textInverse: "#0f0c29",
    border: "#2a2660",
    success: "#00ff88",
    warning: "#ffb347",
    error: "#ff6b6b",
    chartColors: [
      "#00d2ff",
      "#7b68ee",
      "#ff6b6b",
      "#00ff88",
      "#ffb347",
      "#ff69b4",
      "#48dbfb",
      "#a29bfe",
    ],
  },
  typography: {
    titleFont: "SF Pro Display",
    bodyFont: "SF Pro Text",
    monoFont: "SF Mono",
    titleSize: 36,
    subtitleSize: 22,
    bodySize: 16,
    captionSize: 13,
    titleWeight: "700",
    bodyWeight: "normal",
    lineHeight: 1.4,
  },
  spacing: {
    slidePaddingX: 0.9,
    slidePaddingY: 0.6,
    elementGap: 0.3,
    sectionGap: 0.6,
  },
  shapes: {
    cornerRadius: 12,
    lineWidth: 1,
    lineColor: "#3a3680",
  },
  chart: {
    axisColor: "#4a4680",
    gridColor: "#2a2660",
    labelColor: "#9898b8",
    fontFamily: "SF Mono",
  },
  image: {
    borderRadius: 12,
    overlayOpacity: 0.5,
    overlayColor: "#0f0c29",
  },
  density: "high",
  defaultVisualIntensity: "high",
};
